import type { Metadata } from "next";
import { Manrope, Merriweather } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Mikołaj Karla - Portfolio</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${manrope.variable} ${merriweather.variable} antialiased bg-white`}>
        <header className="fixed left-1/2 top-2 -translate-x-1/2 z-50 flex justify-center px-2 sm:px-4 ">
          <Header />
        </header>
        <main className="pt-16 px-2 sm:px-8 max-w-screen-lg mx-auto w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
